AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  solace-stats

  API for statistics on the Solace Coverage Protocol

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    AutoPublishAlias: live
    Tracing: Active
    Environment:
      Variables:
        DEAD_LETTER_TOPIC: arn:aws:sns:us-west-2:151427405638:DeadLetterSnsTopic
        DATA_BUCKET: stats.solace.fi.data
    DeadLetterQueue:
      Type: SNS
      TargetArn: arn:aws:sns:us-west-2:151427405638:DeadLetterSnsTopic
  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Resources:
  # Rest API
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: SolaceStatsApi
      Domain:
        DomainName: stats.solace.fi
        CertificateArn: arn:aws:acm:us-west-2:151427405638:certificate/55b18704-e0db-4ce8-b070-43fc8b0c919d
        Route53:
          HostedZoneId: Z0480029MZJJGNMS3NEJ
      StageName: prod
      TracingEnabled: true
  OptionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceStatsOptionsFunction
      Handler: api/options.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: options
            RestApiId: !Ref RestApi
  FaviconFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceStatsFaviconFunction
      Handler: api/favicon/get.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /favicon.ico
            Method: get
            RestApiId: !Ref RestApi
  IndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceStatsIndexFunction
      Handler: api/get.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref RestApi
  SolaceTotalSupplyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceStatsSolaceTotalSupplyFunction
      Handler: api/SOLACE/totalSupply/get.handler
      Runtime: nodejs14.x
      MemorySize: 1024
      Timeout: 60
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /SOLACE/totalSupply
            Method: get
            RestApiId: !Ref RestApi
  SolaceCirculatingSupplyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceStatsSolaceCirculatingSupplyFunction
      Handler: api/SOLACE/circulatingSupply/get.handler
      Runtime: nodejs14.x
      MemorySize: 1024
      Timeout: 60
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /SOLACE/circulatingSupply
            Method: get
            RestApiId: !Ref RestApi
  XSolaceTotalSupplyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceStatsXSolaceTotalSupplyFunction
      Handler: api/xSOLACE/totalSupply/get.handler
      Runtime: nodejs14.x
      MemorySize: 1024
      Timeout: 60
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /xSOLACE/totalSupply
            Method: get
            RestApiId: !Ref RestApi
  XSolaceCirculatingSupplyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceStatsXSolaceCirculatingSupplyFunction
      Handler: api/xSOLACE/circulatingSupply/get.handler
      Runtime: nodejs14.x
      MemorySize: 1024
      Timeout: 60
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /xSOLACE/circulatingSupply
            Method: get
            RestApiId: !Ref RestApi
  XSolaceV1TotalSupplyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceStatsXSolaceV1TotalSupplyFunction
      Handler: api/xSOLACEv1/totalSupply/get.handler
      Runtime: python3.8
      MemorySize: 1024
      Timeout: 60
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /xSOLACEv1/totalSupply
            Method: get
            RestApiId: !Ref RestApi
  XSolaceV1CirculatingSupplyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceStatsXSolaceV1CirculatingSupplyFunction
      Handler: api/xSOLACEv1/circulatingSupply/get.handler
      Runtime: python3.8
      MemorySize: 1024
      Timeout: 60
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /xSOLACEv1/circulatingSupply
            Method: get
            RestApiId: !Ref RestApi
  SoteriaPolicyDescriptorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceStatsSoteriaPolicyDescriptorFunction
      Handler: api/policy/get.handler
      Runtime: python3.8
      MemorySize: 1024
      Timeout: 60
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /policy
            Method: get
            RestApiId: !Ref RestApi
  SolaceTVLFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceStatsTVLFunction
      Handler: api/tvl/get.handler
      Runtime: python3.8
      MemorySize: 1024
      Timeout: 600
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /tvl
            Method: get
            RestApiId: !Ref RestApi
  SolaceTVLCalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SolaceStatsTVLCalculatorFunction
      Handler: api/tvl/tvl_calculator.main
      Runtime: python3.8
      MemorySize: 1024
      Timeout: 600
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(60 minutes)
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SolaceStatsLambdaExecutionRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: SolaceStatsLambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "sns:Publish"
                Resource: "arn:aws:sns:us-west-2:151427405638:DeadLetterSnsTopic"
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:DeleteObject"
                  - "s3:ListBucket"
                  - "s3:PutObject"
                  - "s3:ReplicateObject"
                  - "s3:RestoreObject"
                Resource: "arn:aws:s3:::stats.solace.fi.data/*"
  # Data Bucket
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: stats.solace.fi.data
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - HEAD
              - GET
            AllowedOrigins:
              - "*"
            AllowedHeaders:
              - "*"
